name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - uses: actions/setup-node@v2
        env:
          CYPRESS_CACHE_FOLDER: C:/Users/runneradmin/AppData/Local/Cypress/Cache
        with:
          node-version: 16

      # - run: npx cypress info

      # - run: sudo apt-get install libnss3-tools && echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      #- run: cd ./src/FsBeacon.Template && yarn install && rm -rf node_modules/gun/examples/iris
      - run: cd ./src/FsBeacon.Template && yarn install --network-timeout 1000000 #&& rm -r -fo node_modules/gun/examples/iris

      - run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.actor }}/index.json --name github -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - uses: cypress-io/github-action@v2
        env:
          GITHUB_READ_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_CACHE_FOLDER: C:/Users/runneradmin/AppData/Local/Cypress/Cache
        with:
          working-directory: ./src/FsBeacon.Template
          build: yarn build:fable
          start: yarn cypress-serve
          command: yarn cypress-run-delay

      - shell: pwsh
        env:
          GITHUB_READ_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd src/FsBeacon.Shared; ./pack.ps1

      - run: cd src/FsBeacon.Shared/bin/Release; dotnet nuget push "*.nupkg" --source github --skip-duplicate

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ./src/FsBeacon.Template/cypress/screenshots

      - uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: ./src/FsBeacon.Template/cypress/screenshots

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: ./src/FsBeacon.Template/cypress/videos

      - uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: ./src/FsBeacon.Template/cypress/videos

      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: hubpeer_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=hub-main

      - uses: docker/build-push-action@v2
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_READ_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          context: .
          file: src/FsBeacon.HubPeer/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.hubpeer_meta.outputs.tags }}
          labels: ${{ steps.hubpeer_meta.outputs.labels }}
          build-args: |
            GITHUB_ACTOR=${{ github.actor }}
            GITHUB_READ_PACKAGES_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - id: gunpeer_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=gun-main

      - uses: docker/build-push-action@v2
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_READ_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          context: .
          file: src/FsBeacon.GunPeer/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.gunpeer_meta.outputs.tags }}
          labels: ${{ steps.gunpeer_meta.outputs.labels }}
