name: build

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: dotnet tool restore
      - run: dotnet paket restore
      - run: dotnet build

      - run: sudo apt-get install libnss3-tools

#      - uses: cypress-io/github-action@v2
#        with:
#          working-directory: ./src/FsBeacon.Tests
#          build: npx cypress info
#          start: yarn serve
#          command: yarn cypress-run

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ./src/FsBeacon.Tests/cypress/screenshots

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: ./src/FsBeacon.Tests/cypress/videos


      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: hubpeer_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/fsbeacon

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: src/FsBeacon.HubPeer/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            type=ref,event=branch
            type=sha
            hub-main
          labels: ${{ steps.hubpeer_meta.outputs.labels }}

      - id: gunpeer_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/fsbeacon

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: src/FsBeacon.GunPeer/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            type=ref,event=branch
            type=sha
            gun-main
          labels: ${{ steps.gunpeer_meta.outputs.labels }}
