name: build

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npx cypress info

      - run: sudo apt-get install libnss3-tools && echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - run: cd ./src/FsBeacon.Template && yarn install

      - uses: cypress-io/github-action@v2
        env:
          GITHUB_READ_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: ./src/FsBeacon.Template
          build: yarn build:fable && rm -rf node_modules/gun/examples/iris
          start: yarn cypress-serve
          command: yarn cypress-run

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ./src/FsBeacon.Template/cypress/screenshots

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: ./src/FsBeacon.Template/cypress/videos

      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: hubpeer_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=hub-main

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: src/FsBeacon.HubPeer/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.hubpeer_meta.outputs.tags }}
          labels: ${{ steps.hubpeer_meta.outputs.labels }}

      - id: gunpeer_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=gun-main

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: src/FsBeacon.GunPeer/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.gunpeer_meta.outputs.tags }}
          labels: ${{ steps.gunpeer_meta.outputs.labels }}
